CREATE TABLE teams (
	LEAGUE_ID VARCHAR(1),
	TEAM_ID VARCHAR(10) PRIMARY KEY NOT NULL,
	MIN_YEAR INT NOT NULL,
	MAX_YEAR INT NOT NULL,
	ABBREVIATION VARCHAR(3) NOT NULL,
	NICKNAME VARCHAR(20) NOT NULL,
	YEARFOUNDED INT NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	ARENA VARCHAR(50) NOT NULL,
	ARENACAPACITY VARCHAR(5),
	"OWNER" VARCHAR(50) NOT NULL,
	GENERALMANAGER VARCHAR(50) NOT NULL,
	HEADCOACH VARCHAR(50) NOT NULL,
	DLEAGUEAFFILIATION VARCHAR(50) NOT NULL
);

CREATE TABLE players (
	PLAYER_NAME VARCHAR(50) NOT NULL,
	TEAM_ID VARCHAR(10) NOT NULL,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID),
	PLAYER_ID VARCHAR(10) PRIMARY KEY NOT NULL,
	SEASON INT
);

CREATE TABLE games (
	GAME_ID VARCHAR(10) PRIMARY KEY NOT NULL,
	GAME_STATUS_TEXT VARCHAR(5) NOT NULL,
	HOME_TEAM_ID VARCHAR(10),
	FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAMS (TEAM_ID),
	VISITOR_TEAM_ID VARCHAR (10) NOT NULL,
	FOREIGN KEY (VISITOR_TEAM_ID) REFERENCES TEAMS (TEAM_ID),
	SEASON DATE NOT NULL,
	TEAM_ID_HOME VARCHAR (10) NOT NULL,
	FOREIGN KEY (TEAM_ID_HOME) REFERENCES TEAMS (TEAM_ID),
	PTS_HOME INT NOT NULL,
	FG_PCT_HOME DECIMAL NOT NULL,
	FT_PCT_HOME DECIMAL NOT NULL,
	FG3_PCT_HOME DECIMAL NOT NULL,
	AST_HOME INT NOT NULL,
	REB_HOME INT NOT NULL,
	TEAM_ID_AWAY VARCHAR(10) NOT NULL,
	FOREIGN KEY (TEAM_ID_AWAY) REFERENCES TEAMS (TEAM_ID),
	PTS_AWAY INT NOT NULL,
	FG_PCT_AWAY DECIMAL NOT NULL,
	FT_PCT_AWAY DECIMAL NOT NULL,
	FG3_PCT_AWAY DECIMAL NOT NULL,
	AST_AWAY INT NOT NULL,
	REB_AWAY INT NOT NULL,
	HOME_TEAM_WINS INT NOT NULL
);

CREATE TABLE games_details (
	GAME_ID VARCHAR(10) NOT NULL,
	FOREIGN KEY (GAME_ID) REFERENCES GAMES (GAME_ID),
	TEAM_ID VARCHAR(10) NOT NULL,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID),
	TEAM_ABBREVIATION VARCHAR (3) NOT NULL,
	TEAM_CITY VARCHAR(50) NOT NULL,
	PLAYER_ID VARCHAR(10) NOT NULL,
	FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (PLAYER_ID),
	PLAYER_NAME VARCHAR (50) NOT NULL,
	NICKNAME VARCHAR (50) NOT NULL,
	START_POSITION VARCHAR,
	COMMENT VARCHAR,
	MIN VARCHAR,
	FGM INT,
	FGA INT,
	FG_PCT DECIMAL,
	FG3M INT,
	FG3A INT,
	FG3_PCT DECIMAL,
	FTM INT,
	FTA INT,
	FT_PCT DECIMAL, 
	OREB INT,
	DREB INT,
	REB INT,
	AST INT,
	STL INT,
	BLK INT,
	"TO" INT,
	PF INT,
	PTS INT,
	PLUS_MINUS INT
);

CREATE TABLE ranking (
	TEAM_ID VARCHAR(10) NOT NULL,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID),
	LEAGUE_ID VARCHAR(1) NOT NULL,
	SEASON_ID VARCHAR NOT NULL,
	STANDINGSDATE DATE, 
	CONFERENCE VARCHAR(4) NOT NULL,
	TEAM VARCHAR(50) NOT NULL,
	G INT NOT NULL,
	W INT NOT NULL,
	L INT NOT NULL,
	W_PCT DECIMAL NOT NULL,
	HOME_RECORD DATE,
	ROAD_RECORD DATE,
	RETURNTOPLAY VARCHAR
);


DROP TABLE ranking;
DROP TABLE games_details;
DROP TABLE games;
DROP TABLE players;
DROP TABLE teams;
